columns:
  customerID: object
  gender: object
  SeniorCitizen: int64
  Partner: object
  Dependents: object
  tenure: int64
  PhoneService: object
  MultipleLines: object
  InternetService: object
  OnlineSecurity: object
  OnlineBackup: object
  DeviceProtection: object
  TechSupport: object
  StreamingTV: object
  StreamingMovies: object
  Contract: object
  PaperlessBilling: object
  PaymentMethod: object
  MonthlyCharges: float64
  TotalCharges: object
  Churn: object

numerical_columns:
  - SeniorCitizen
  - tenure
  - MonthlyCharges

categorical_columns:
  - customerID
  - gender
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod
  - TotalCharges
  - Churn

target_column: Churn